### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by dhalucario** [mtcw99/msq-rs#1]
I am trying to use the library on Linux. It complies successfully but it doesn't seem to work. It just gets stuck here.
It works fine on Windows so I assume this might be a bug with the library since I don't wee a reason why this wouldn't work.

https://gitlab.com/dhalucario/tf2-cqp/-/blob/devel/linux/src/casual_quickplay_controller.rs#L70

**Comment by dhalucario** [comment]
After a bit of testing I think I found the issue in specific. Its not a Linux issue, but when you give gametype an empty vector or no gametype at all it gets stuck forever.

**Comment by dhalucario** [comment]
Nevermind, I think I misunderstood how the filters work and the fact that the nand and the end are related in the filters.

**Comment by nullsystem** [comment]
The doc/guide will need a bit of polish anyway. I'll figure out what to put in the doc + readme to improve it, especially since the nand/nor/end methods aren't really explained properly.

**Comment by nullsystem** [comment]
I'm reopening this issue and will close it once documentation improved to a satisfactory level.

**Comment by nullsystem** [comment]
Documentation has improved, ready for v0.2.0
